version: 0.0
os: linux
hooks: # Deploy life cycle events
  Services:
    - location: ./docker.sh
      timeout: 300
      runas: root
#  BeforeInstall:
#    - location: scripts/before_install.sh
#      timeout: 300
#      runas: root
#  AfterInstall:
#    - location: scripts/after_install.sh
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
